# Generated by Django 4.1 on 2024-08-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='THPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('diachi', models.CharField(max_length=500)),
                ('quan', models.CharField(max_length=500)),
                ('ghichu', models.CharField(blank=True, max_length=500)),
                ('toan', models.FloatField()),
                ('van', models.FloatField()),
                ('anh', models.FloatField()),
            ],
        ),
    ]
