# Generated by Django 4.1 on 2024-08-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thpt',
            name='anh',
        ),
        migrations.RemoveField(
            model_name='thpt',
            name='toan',
        ),
        migrations.RemoveField(
            model_name='thpt',
            name='van',
        ),
        migrations.AddField(
            model_name='thpt',
            name='isChuyen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thpt',
            name='monchuyen',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='thpt',
            name='nv1',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='thpt',
            name='nv2',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='thpt',
            name='nv3',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
