# Generated by Django 4.1 on 2024-08-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thpt',
            options={'ordering': ['-nv1', '-nv2', '-nv3']},
        ),
    ]
