# Generated by Django 4.1 on 2024-08-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_thpt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='thpt',
            name='anh',
            field=models.ImageField(blank=True, null=True, upload_to='thpt/'),
        ),
    ]
